### ISSUE TITLE
No option to run workflow & When i forked the repo to try that the builds always fail

### ISSUE THREAD

**Issue by RadioactiveBen** [tedsteen/nes-bundler#123]
![image_2024-05-15_173022365](https://github.com/tedsteen/nes-bundler/assets/93561387/a3c38388-6214-420a-9e13-7c558e0dc34d)
![image_2024-05-15_173110585](https://github.com/tedsteen/nes-bundler/assets/93561387/a1a71f4e-a7b8-4388-8625-82bdf76a429a)
this what i see

**Comment by RadioactiveBen** [comment]
i also understand that stuff like this is diffucult i know i could never do this or static recomp

**Comment by tedsteen** [comment]
Oh, haha that's a bummer!

I wonder why? Perhaps it is only possible to run a workflow if you are a collaborator of the repository?
I will have to look into this..

**Comment by RadioactiveBen** [comment]
i found this if it helps :) https://stackoverflow.com/questions/76030960/whats-the-proper-way-to-use-github-actions-with-a-public-repo-if-we-absolutely

**Comment by RadioactiveBen** [comment]
would figuring out a way to run it locally work?? to fix this problem

**Comment by RadioactiveBen** [comment]
i keep getting this error in my fork "Mail command failed: 530-5.7.0 Authentication Required. For more information, go to
530 5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1ef0bada410sm110901035ad.69 - gsmtp"

**Comment by tedsteen** [comment]
> i keep getting this error in my fork "Mail command failed: 530-5.7.0 Authentication Required. For more information, go to 530 5.7.0 https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1ef0bada410sm110901035ad.69 - gsmtp"

Yeah, to make it work on your own you need a lot of setup... You need to either disable the mail sending or add credentials for it.
But more importantly you need to setup the certificates to sign the binaries which is really really messy.

I will have a look at it and make it work in this repo some how !

**Comment by tedsteen** [comment]
I created this if you would like to try it out
https://nes-bundler.com/

I will update the documentation when I have more time, but this basically replace the manual triggering of the runner.

You put your email and bundle configuration zip on that page and press "Bundle!" and off you go!

**Comment by RadioactiveBen** [comment]
i will take a look thanks so much

**Comment by RadioactiveBen** [comment]
it works thanks so much

**Comment by tedsteen** [comment]
> i wonder is there ways to compile it with a gui and run it offline and locally (i dont expect u to do this in the near future or ever for that matter as this way works perfectly but still) or even make one compatible with snes or other 6502 consoles

If you would like to try it out locally on your computer you can simply check the "Try it out" section in the readme: https://github.com/tedsteen/nes-bundler#try-it-out

Regarding snes and other 6502 consoles.. I would love to make a snes-bundler! perhaps one day :)

**Comment by tedsteen** [comment]
Ok updated the documentation as well, I think we can close this!
If you have any issues with it reopen the issue!
