### ISSUE TITLE
whenever i put in a rom of my own it gives me data man as the rom

### ISSUE THREAD

**Issue by RadioactiveBen** [tedsteen/nes-bundler#126]

**Comment by tedsteen** [comment]
How do you compress your zip file?
Check this for a working example
https://github.com/tedsteen/nes-bundler/blob/master/config/prepare.sh

**Comment by RadioactiveBen** [comment]
i think i compressed it wrong i am testing that script

**Comment by RadioactiveBen** [comment]
it bundles and emails me it i cant get it to open it just is a trasparent window

**Comment by tedsteen** [comment]
Does it work when you juat try it out using this method?

https://github.com/tedsteen/nes-bundler?tab=readme-ov-file#try-it-out

**Comment by tedsteen** [comment]
Did you manage?
I will close this issue unless you still have issues with this
