### ISSUE TITLE
fullscreen mode only *VERSION*

### ISSUE THREAD

**Issue by alphadoric** [tedsteen/nes-bundler#127]
Please launch an version that execute in full screen mode only (without title bar), it is useful to launch game in steam platform, thanks

**Comment by tedsteen** [comment]
Did you try this?
https://github.com/tedsteen/nes-bundler/blob/master/config/config.yaml#L31

And if you did, what is missing?

**Comment by alphadoric** [comment]
please I'm confused, I don't understand how to get my own rom to work, I would like a walkthrough please (step by step)

**Comment by alphadoric** [comment]
okay but what is pallete.pal file ? I'm preparing my rom to bundle, .....

**Comment by tedsteen** [comment]
For more details about configuration check out https://github.com/tedsteen/nes-bundler/blob/master/config/README.md

**Comment by alphadoric** [comment]
# Starts the game in fullscreen if true
start_in_fullscreen: true

Correct ?

**Comment by tedsteen** [comment]
> # Starts the game in fullscreen if true
> 
> start_in_fullscreen: true
> 
> 
> 
> Correct ?

Yes that's correct

**Comment by tedsteen** [comment]
Did you manage?
I will close this issue unless you still have issues with this.
